-- ==============================================================================
-- SITIA - Migración de Base de Datos para Producción: Remitos de Devolución
-- Base de Datos: inventario_insumos_v1
-- Nomenclatura: nnnn_yyyy_DEV (Ej: 0001_2026_DEV)
-- Fecha: 2026-10-01 17:44:19
-- ==============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- ------------------------------------------------------------------------------
-- 1. Estructura: Secuencia Anual de Devoluciones
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `remito_devolucion_secuencia` (
    `anio` INT NOT NULL,
    `ultimo` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`anio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------------------------
-- 2. Estructura: Cabecera de Remitos de Devolución
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `remitos_devolucion` (
    `id_remito_devolucion` INT NOT NULL AUTO_INCREMENT,
    `numero_devolucion` VARCHAR(50) NOT NULL,
    `id_remito_origen` INT NOT NULL,
    `fecha_devolucion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `id_usuario_receptor` INT NOT NULL,
    `persona_entrega` VARCHAR(150) DEFAULT NULL,
    `observaciones` TEXT DEFAULT NULL,
    `remito_firmado` VARCHAR(255) DEFAULT NULL,
    `estado` ENUM('Confirmado', 'Anulado') NOT NULL DEFAULT 'Confirmado',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id_remito_devolucion`),
    UNIQUE KEY `uk_numero_devolucion` (`numero_devolucion`),
    KEY `idx_remdev_origen` (`id_remito_origen`),
    KEY `idx_remdev_fecha` (`fecha_devolucion`),
    KEY `idx_remdev_usuario` (`id_usuario_receptor`),
    CONSTRAINT `fk_remdev_remito` FOREIGN KEY (`id_remito_origen`) REFERENCES `remitos` (`id_remito`) ON DELETE RESTRICT,
    CONSTRAINT `fk_remdev_usuario` FOREIGN KEY (`id_usuario_receptor`) REFERENCES `usuarios` (`id_usuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------------------------
-- 3. Estructura: Detalle de Insumos Devueltos
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `remitos_devolucion_detalle` (
    `id_remito_devolucion_detalle` INT NOT NULL AUTO_INCREMENT,
    `id_remito_devolucion` INT NOT NULL,
    `id_insumo` INT NOT NULL,
    `cantidad` INT NOT NULL DEFAULT 1,
    `destino` ENUM('disponible', 'baja') NOT NULL DEFAULT 'disponible',
    `motivo_baja` VARCHAR(255) DEFAULT NULL,
    `estado_fisico` VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (`id_remito_devolucion_detalle`),
    KEY `idx_remdev_det_rem` (`id_remito_devolucion`),
    KEY `idx_remdev_det_ins` (`id_insumo`),
    CONSTRAINT `fk_remdev_det_cab` FOREIGN KEY (`id_remito_devolucion`) REFERENCES `remitos_devolucion` (`id_remito_devolucion`) ON DELETE CASCADE,
    CONSTRAINT `fk_remdev_det_ins` FOREIGN KEY (`id_insumo`) REFERENCES `insumos` (`id_insumo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------------------------
-- 4. Aseguramiento de columna cantidad_devuelta en remitos_detalle (Idempotente)
-- ------------------------------------------------------------------------------
SET @col_exist = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'remitos_detalle' AND COLUMN_NAME = 'cantidad_devuelta');
SET @sql_stmt = IF(@col_exist = 0, 'ALTER TABLE remitos_detalle ADD COLUMN cantidad_devuelta INT NOT NULL DEFAULT 0 AFTER cantidad', 'SELECT "Columna cantidad_devuelta ya existe"');
PREPARE stmt FROM @sql_stmt;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ==============================================================================
-- 5. Migración de Devoluciones Históricas Retroactivas
-- ==============================================================================

INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0001_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '1_2026_hist' LIMIT 1), '2026-01-13 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Lujan Teruel', 'Migración histórica de devolución de Remito #1_2026_hist', 'Confirmado', '2026-01-13 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0001_2026_DEV'), 142, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0002_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0054_2026' LIMIT 1), '2026-03-02 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Eliana Kostiti', 'Migración histórica de devolución de Remito #0054_2026', 'Confirmado', '2026-03-02 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0002_2026_DEV'), 220, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0002_2026_DEV'), 221, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0003_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '4_2026_hist' LIMIT 1), '2026-03-02 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Arnoldo Truchi', 'Migración histórica de devolución de Remito #4_2026_hist', 'Confirmado', '2026-03-02 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0003_2026_DEV'), 225, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0004_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '23_2026_hist' LIMIT 1), '2026-03-03 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Jesica Muñoz', 'Migración histórica de devolución de Remito #23_2026_hist', 'Confirmado', '2026-03-03 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0004_2026_DEV'), 244, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0005_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '9_2025_hist' LIMIT 1), '2026-03-04 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Sebastian Sanchez', 'Migración histórica de devolución de Remito #9_2025_hist', 'Confirmado', '2026-03-04 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0005_2026_DEV'), 118, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0006_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '22_2025_hist' LIMIT 1), '2026-03-10 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Evelyn Aylen Ramirez Tomasini', 'Migración histórica de devolución de Remito #22_2025_hist', 'Confirmado', '2026-03-10 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0006_2026_DEV'), 131, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0007_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '31_2026_hist' LIMIT 1), '2026-04-06 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ivana Blanco', 'Migración histórica de devolución de Remito #31_2026_hist', 'Confirmado', '2026-04-06 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0007_2026_DEV'), 252, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0008_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '14_2026_hist' LIMIT 1), '2026-04-20 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Rodrigo Vera', 'Migración histórica de devolución de Remito #14_2026_hist', 'Confirmado', '2026-04-20 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0008_2026_DEV'), 235, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0009_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0108_2026' LIMIT 1), '2026-04-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Alejandra Barros', 'Migración histórica de devolución de Remito #0108_2026', 'Confirmado', '2026-04-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0009_2026_DEV'), 205, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0009_2026_DEV'), 311, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0010_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '4_2025_hist' LIMIT 1), '2026-05-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Leandro Gutierrez', 'Migración histórica de devolución de Remito #4_2025_hist', 'Confirmado', '2026-05-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0010_2026_DEV'), 113, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0011_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '5_2025_hist' LIMIT 1), '2026-05-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Leandro Gutierrez', 'Migración histórica de devolución de Remito #5_2025_hist', 'Confirmado', '2026-05-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0011_2026_DEV'), 114, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0012_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '6_2025_hist' LIMIT 1), '2026-05-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Leandro Gutierrez', 'Migración histórica de devolución de Remito #6_2025_hist', 'Confirmado', '2026-05-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0012_2026_DEV'), 115, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0013_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '7_2025_hist' LIMIT 1), '2026-05-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Leandro Gutierrez', 'Migración histórica de devolución de Remito #7_2025_hist', 'Confirmado', '2026-05-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0013_2026_DEV'), 116, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0014_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '23_2025_hist' LIMIT 1), '2026-05-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Alejandra Barros', 'Migración histórica de devolución de Remito #23_2025_hist', 'Confirmado', '2026-05-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0014_2026_DEV'), 132, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0015_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '24_2025_hist' LIMIT 1), '2026-05-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Alejandra Barros', 'Migración histórica de devolución de Remito #24_2025_hist', 'Confirmado', '2026-05-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0015_2026_DEV'), 133, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0016_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '25_2025_hist' LIMIT 1), '2026-05-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Alejandra Barros', 'Migración histórica de devolución de Remito #25_2025_hist', 'Confirmado', '2026-05-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0016_2026_DEV'), 134, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0017_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0117_2026' LIMIT 1), '2026-05-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Luciano Crovella', 'Migración histórica de devolución de Remito #0117_2026', 'Confirmado', '2026-05-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0017_2026_DEV'), 134, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0018_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '55_2026_hist' LIMIT 1), '2026-05-07 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ayelen Peralta', 'Migración histórica de devolución de Remito #55_2026_hist', 'Confirmado', '2026-05-07 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0018_2026_DEV'), 335, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0019_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '56_2026_hist' LIMIT 1), '2026-05-11 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Javier Sanz', 'Migración histórica de devolución de Remito #56_2026_hist', 'Confirmado', '2026-05-11 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0019_2026_DEV'), 336, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0020_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0129_2026' LIMIT 1), '2026-05-13 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Nayibe Favreau', 'Migración histórica de devolución de Remito #0129_2026', 'Confirmado', '2026-05-13 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0020_2026_DEV'), 244, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0020_2026_DEV'), 167, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0021_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '59_2026_hist' LIMIT 1), '2026-05-19 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Nayibe Favreau', 'Migración histórica de devolución de Remito #59_2026_hist', 'Confirmado', '2026-05-19 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0021_2026_DEV'), 346, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0022_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '20_2026_hist' LIMIT 1), '2026-05-22 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Andrea Relmuan', 'Migración histórica de devolución de Remito #20_2026_hist', 'Confirmado', '2026-05-22 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0022_2026_DEV'), 241, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0023_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0048_2026' LIMIT 1), '2026-06-03 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Vanesa Gimenez', 'Migración histórica de devolución de Remito #0048_2026', 'Confirmado', '2026-06-03 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0023_2026_DEV'), 210, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0024_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '63_2026_hist' LIMIT 1), '2026-06-03 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Vanesa Gimenez', 'Migración histórica de devolución de Remito #63_2026_hist', 'Confirmado', '2026-06-03 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0024_2026_DEV'), 390, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0025_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '64_2026_hist' LIMIT 1), '2026-06-05 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Vanesa Gimenez', 'Migración histórica de devolución de Remito #64_2026_hist', 'Confirmado', '2026-06-05 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0025_2026_DEV'), 391, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0026_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0046_2026' LIMIT 1), '2026-06-12 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Heber Gonzalez', 'Migración histórica de devolución de Remito #0046_2026', 'Confirmado', '2026-06-12 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0026_2026_DEV'), 210, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0027_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '66_2026_hist' LIMIT 1), '2026-06-12 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Joaquin Villaverde', 'Migración histórica de devolución de Remito #66_2026_hist', 'Confirmado', '2026-06-12 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0027_2026_DEV'), 396, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0028_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '67_2026_hist' LIMIT 1), '2026-06-12 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Joaquin Villaverde', 'Migración histórica de devolución de Remito #67_2026_hist', 'Confirmado', '2026-06-12 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0028_2026_DEV'), 397, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0029_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '68_2026_hist' LIMIT 1), '2026-06-12 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Heber Gonzalez', 'Migración histórica de devolución de Remito #68_2026_hist', 'Confirmado', '2026-06-12 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0029_2026_DEV'), 398, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0030_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0016_2026' LIMIT 1), '2026-06-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Emerson Caceres', 'Migración histórica de devolución de Remito #0016_2026', 'Confirmado', '2026-06-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0030_2026_DEV'), 162, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0031_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '13_2026_hist' LIMIT 1), '2026-06-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Barbara Díaz', 'Migración histórica de devolución de Remito #13_2026_hist', 'Confirmado', '2026-06-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0031_2026_DEV'), 234, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0032_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0160_2026' LIMIT 1), '2026-07-08 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Caupolican Rodriguez', 'Migración histórica de devolución de Remito #0160_2026', 'Confirmado', '2026-07-08 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0032_2026_DEV'), 157, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0033_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '28_2025_hist' LIMIT 1), '2026-07-14 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Lujan Teruel', 'Migración histórica de devolución de Remito #28_2025_hist', 'Confirmado', '2026-07-14 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0033_2026_DEV'), 137, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0034_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0171_2026' LIMIT 1), '2026-07-31 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Facundo Toledo', 'Migración histórica de devolución de Remito #0171_2026', 'Confirmado', '2026-07-31 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0034_2026_DEV'), 4, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0035_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '86_2026_hist' LIMIT 1), '2026-07-31 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Fiorella Migliore', 'Migración histórica de devolución de Remito #86_2026_hist', 'Confirmado', '2026-07-31 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0035_2026_DEV'), 430, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0036_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0181_2026' LIMIT 1), '2026-09-07 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Francisco Tomas Gonzalez Magni', 'Migración histórica de devolución de Remito #0181_2026', 'Confirmado', '2026-09-07 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0036_2026_DEV'), 134, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0037_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0182_2026' LIMIT 1), '2026-09-08 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Francisco Tomas Gonzalez Magni', 'Migración histórica de devolución de Remito #0182_2026', 'Confirmado', '2026-09-08 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0037_2026_DEV'), 464, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0038_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0183_2026' LIMIT 1), '2026-09-08 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Francisco Tomas Gonzalez Magni', 'Migración histórica de devolución de Remito #0183_2026', 'Confirmado', '2026-09-08 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0038_2026_DEV'), 145, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0039_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '230_2026_hist' LIMIT 1), '2026-09-14 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ricardo Araya', 'Migración histórica de devolución de Remito #230_2026_hist', 'Confirmado', '2026-09-14 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0039_2026_DEV'), 731, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0040_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '26_2025_hist' LIMIT 1), '2026-09-15 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Sebastian Sanchez', 'Migración histórica de devolución de Remito #26_2025_hist', 'Confirmado', '2026-09-15 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0040_2026_DEV'), 135, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0041_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '169_2026_hist' LIMIT 1), '2026-09-16 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Luis Dalfonso', 'Migración histórica de devolución de Remito #169_2026_hist', 'Confirmado', '2026-09-16 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0041_2026_DEV'), 559, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0042_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '109_2025_hist' LIMIT 1), '2026-09-23 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Fiorela Maglione', 'Migración histórica de devolución de Remito #109_2025_hist', 'Confirmado', '2026-09-23 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0042_2026_DEV'), 109, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0043_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '1_2025_hist' LIMIT 1), '2026-09-23 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Fiorela Maglione', 'Migración histórica de devolución de Remito #1_2025_hist', 'Confirmado', '2026-09-23 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0043_2026_DEV'), 110, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0044_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '2_2025_hist' LIMIT 1), '2026-09-23 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Fiorela Maglione', 'Migración histórica de devolución de Remito #2_2025_hist', 'Confirmado', '2026-09-23 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0044_2026_DEV'), 111, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0045_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '3_2025_hist' LIMIT 1), '2026-09-23 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Fiorela Maglione', 'Migración histórica de devolución de Remito #3_2025_hist', 'Confirmado', '2026-09-23 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0045_2026_DEV'), 112, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0046_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0059_2026' LIMIT 1), '2026-09-23 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Rocio Juarez', 'Migración histórica de devolución de Remito #0059_2026', 'Confirmado', '2026-09-23 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0046_2026_DEV'), 207, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0046_2026_DEV'), 262, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0046_2026_DEV'), 157, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0047_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0065_2026' LIMIT 1), '2026-09-23 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Rocio Juarez', 'Migración histórica de devolución de Remito #0065_2026', 'Confirmado', '2026-09-23 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0047_2026_DEV'), 145, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0047_2026_DEV'), 283, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0047_2026_DEV'), 284, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0047_2026_DEV'), 144, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0048_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0137_2026' LIMIT 1), '2026-09-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ayelen Peralta', 'Migración histórica de devolución de Remito #0137_2026', 'Confirmado', '2026-09-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0048_2026_DEV'), 356, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0049_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '171_2026_hist' LIMIT 1), '2026-09-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ricardo Araya', 'Migración histórica de devolución de Remito #171_2026_hist', 'Confirmado', '2026-09-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0049_2026_DEV'), 561, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0050_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '175_2026_hist' LIMIT 1), '2026-09-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ricardo Araya', 'Migración histórica de devolución de Remito #175_2026_hist', 'Confirmado', '2026-09-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0050_2026_DEV'), 565, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0051_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '187_2026_hist' LIMIT 1), '2026-09-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'RIcardo Araya', 'Migración histórica de devolución de Remito #187_2026_hist', 'Confirmado', '2026-09-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0051_2026_DEV'), 577, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0052_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '195_2026_hist' LIMIT 1), '2026-09-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ricardo Araya', 'Migración histórica de devolución de Remito #195_2026_hist', 'Confirmado', '2026-09-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0052_2026_DEV'), 585, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0053_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '219_2026_hist' LIMIT 1), '2026-09-29 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ricardo Araya', 'Migración histórica de devolución de Remito #219_2026_hist', 'Confirmado', '2026-09-29 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0053_2026_DEV'), 609, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0054_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '240_2026_hist' LIMIT 1), '2026-09-30 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ayelen Peralta', 'Migración histórica de devolución de Remito #240_2026_hist', 'Confirmado', '2026-09-30 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0054_2026_DEV'), 779, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0054_2026_DEV'), 780, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0054_2026_DEV'), 5, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0054_2026_DEV'), 291, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0055_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '262_2026_hist' LIMIT 1), '2026-09-30 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ricardo Araya', 'Migración histórica de devolución de Remito #262_2026_hist', 'Confirmado', '2026-09-30 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0055_2026_DEV'), 1248, 1, 'disponible', 'bueno');
INSERT INTO remitos_devolucion (numero_devolucion, id_remito_origen, fecha_devolucion, id_usuario_receptor, persona_entrega, observaciones, estado, created_at) VALUES ('0056_2026_DEV', (SELECT id_remito FROM remitos WHERE numero_remito = '0206_2026' LIMIT 1), '2026-09-30 12:00:00', COALESCE((SELECT id_usuario FROM usuarios WHERE username = 'admin' LIMIT 1), 10), 'Ricardo Araya', 'Migración histórica de devolución de Remito #0206_2026', 'Confirmado', '2026-09-30 12:00:00');
INSERT INTO remitos_devolucion_detalle (id_remito_devolucion, id_insumo, cantidad, destino, estado_fisico) VALUES ((SELECT id_remito_devolucion FROM remitos_devolucion WHERE numero_devolucion = '0056_2026_DEV'), 1250, 1, 'disponible', 'bueno');

-- ------------------------------------------------------------------------------
-- 6. Inicialización de la Secuencia para el año 2026
-- ------------------------------------------------------------------------------
INSERT INTO remito_devolucion_secuencia (anio, ultimo) VALUES (2026, 56) ON DUPLICATE KEY UPDATE ultimo = GREATEST(ultimo, 56);

SET FOREIGN_KEY_CHECKS = 1;

-- ==============================================================================
-- Fin de Migración. Total remitos DEV creados: 56 | Ítems: 67
-- ==============================================================================